package main

import (
	"encoding/json"
	"fmt"
	"os"
	"regexp"
	"strings"
	"sync"
)

var configMu sync.RWMutex

func jsonConfigPath() string {
	p := *flagConfig
	if strings.HasSuffix(p, ".lua") {
		return p[:len(p)-4] + ".json"
	}
	return p + ".json"
}

func loadConfig() (map[string]any, error) {
	configMu.RLock()
	defer configMu.RUnlock()

	data, err := os.ReadFile(jsonConfigPath())
	if err != nil {
		if os.IsNotExist(err) {
			return map[string]any{
				"streams":  map[string]any{},
				"settings": map[string]any{},
			}, nil
		}
		return nil, err
	}

	var cfg map[string]any
	if err := json.Unmarshal(data, &cfg); err != nil {
		return nil, err
	}
	return cfg, nil
}

func saveConfig(cfg map[string]any) error {
	configMu.Lock()
	defer configMu.Unlock()

	if err := os.MkdirAll(dirOf(jsonConfigPath()), 0755); err != nil {
		return err
	}
	data, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return err
	}
	if err := os.WriteFile(jsonConfigPath(), data, 0644); err != nil {
		return err
	}

	// also write Lua config alongside JSON
	lua := jsonToLua(cfg)
	return os.WriteFile(*flagConfig, []byte(lua), 0644)
}

func dirOf(path string) string {
	i := strings.LastIndex(path, "/")
	if i < 0 {
		return "."
	}
	return path[:i]
}

// --- JSON → Lua ---

// anyStr extracts a string representation from map values of various types.
func anyStr(v any) string {
	switch x := v.(type) {
	case string:
		return x
	case float64:
		if x == float64(int(x)) {
			return fmt.Sprintf("%d", int(x))
		}
		return fmt.Sprintf("%g", x)
	case int:
		return fmt.Sprintf("%d", x)
	case bool:
		if x {
			return "true"
		}
		return "false"
	}
	return ""
}

// convertDvbInput converts "dvb://6#pnr=5601" → "dvb://dvb6#pnr=5601"
var reDvbNum = regexp.MustCompile(`^dvb://(\d+)(#.*)$`)

func convertDvbInput(url string) string {
	if m := reDvbNum.FindStringSubmatch(url); m != nil {
		return fmt.Sprintf("dvb://dvb%s%s", m[1], m[2])
	}
	return url
}

func jsonToLua(cfg map[string]any) string {
	var sb strings.Builder
	sb.WriteString("-- Generated by astra-api\n\n")

	// dvb_tune blocks for each adapter
	adapters, _ := cfg["adapters"].(map[string]any)
	for adapterNum, v := range adapters {
		a, ok := v.(map[string]any)
		if !ok {
			continue
		}
		dvbType := strings.TrimPrefix(anyStr(a["dvb_type"]), "DVB-") // "DVB-S2" → "S2"
		if dvbType == "" {
			dvbType = "S2"
		}
		sb.WriteString(fmt.Sprintf("dvb%s = dvb_tune({\n", adapterNum))
		sb.WriteString(fmt.Sprintf("  type = %q,\n", dvbType))

		isSat := dvbType == "S" || dvbType == "S2"
		isTer := dvbType == "T" || dvbType == "T2" || dvbType == "ATSC" || dvbType == "ISDB-T"
		isCab := dvbType == "C" || dvbType == "C2"

		if isSat {
			tp := fmt.Sprintf("%s:%s:%s", anyStr(a["frequency"]), anyStr(a["polarization"]), anyStr(a["symbolrate"]))
			sb.WriteString(fmt.Sprintf("  tp = %q,\n", tp))
			lnb := fmt.Sprintf("%s:%s:%s", anyStr(a["lof1"]), anyStr(a["lof2"]), anyStr(a["slof"]))
			sb.WriteString(fmt.Sprintf("  lnb = %q,\n", lnb))
		} else if isTer {
			tp := fmt.Sprintf("%s:%s", anyStr(a["frequency"]), anyStr(a["bandwidth"]))
			sb.WriteString(fmt.Sprintf("  tp = %q,\n", tp))
		} else if isCab {
			tp := fmt.Sprintf("%s:%s", anyStr(a["frequency"]), anyStr(a["symbolrate"]))
			sb.WriteString(fmt.Sprintf("  tp = %q,\n", tp))
		}
		sb.WriteString(fmt.Sprintf("  adapter = %s,\n", anyStr(a["adapter"])))
		if dev := anyStr(a["device"]); dev != "" && dev != "0" {
			sb.WriteString(fmt.Sprintf("  device = %s,\n", dev))
		}
		sb.WriteString("})\n\n")
	}

	// newcamd({}) blocks — cam_id = newcamd({...})
	cams, _ := cfg["cams"].(map[string]any)
	for camID, v := range cams {
		c, ok := v.(map[string]any)
		if !ok {
			continue
		}
		sb.WriteString(fmt.Sprintf("%s = newcamd({\n", camID))
		sb.WriteString(fmt.Sprintf("  name = %q,\n", anyStr(c["name"])))
		sb.WriteString(fmt.Sprintf("  host = %q,\n", anyStr(c["host"])))
		sb.WriteString(fmt.Sprintf("  port = %s,\n", anyStr(c["port"])))
		sb.WriteString(fmt.Sprintf("  user = %q,\n", anyStr(c["user"])))
		sb.WriteString(fmt.Sprintf("  pass = %q,\n", anyStr(c["pass"])))
		sb.WriteString(fmt.Sprintf("  key  = %q,\n", anyStr(c["key"])))
		if v, ok := c["disable_emm"].(bool); ok {
			sb.WriteString(fmt.Sprintf("  disable_emm = %v,\n", v))
		}
		if t := anyStr(c["timeout"]); t != "" && t != "0" {
			sb.WriteString(fmt.Sprintf("  timeout = %s,\n", t))
		}
		sb.WriteString("})\n\n")
	}

	// make_channel blocks for streams
	streams, _ := cfg["streams"].(map[string]any)
	for _, v := range streams {
		s, ok := v.(map[string]any)
		if !ok {
			continue
		}
		sb.WriteString("make_channel({\n")
		for _, key := range []string{"name", "id", "type"} {
			if val, ok := s[key].(string); ok && val != "" {
				sb.WriteString(fmt.Sprintf("  %s=%q,\n", key, val))
			}
		}
		if enable, ok := s["enable"].(bool); ok {
			sb.WriteString(fmt.Sprintf("  enable=%v,\n", enable))
		}
		if input := toStringSliceLua(s["input"]); len(input) > 0 {
			converted := make([]string, len(input))
			for i, u := range input {
				converted[i] = convertDvbInput(u)
			}
			sb.WriteString(fmt.Sprintf("  input={%s},\n", joinQuoted(converted)))
		}
		if output := toStringSliceLua(s["output"]); len(output) > 0 {
			sb.WriteString(fmt.Sprintf("  output={%s},\n", joinQuoted(output)))
		}
		// BISS key
		if biss := anyStr(s["biss"]); biss != "" {
			sb.WriteString(fmt.Sprintf("  biss=%q,\n", biss))
		}
		// CAM reference (variable name stored as string)
		if cam := anyStr(s["cam"]); cam != "" {
			sb.WriteString(fmt.Sprintf("  cam=%s,\n", cam))
		}
		sb.WriteString("})\n\n")
	}
	return sb.String()
}

func toStringSliceLua(v any) []string {
	var out []string
	switch x := v.(type) {
	case []any:
		for _, item := range x {
			if s, ok := item.(string); ok {
				out = append(out, s)
			}
		}
	case []string:
		out = x
	}
	return out
}

func joinQuoted(ss []string) string {
	parts := make([]string, len(ss))
	for i, s := range ss {
		parts[i] = fmt.Sprintf("%q", s)
	}
	return strings.Join(parts, ",")
}

// --- Lua → JSON ---

var reString = regexp.MustCompile(`(\w+)\s*=\s*"([^"]*)"`)
var reStringSingle = regexp.MustCompile(`(\w+)\s*=\s*'([^']*)'`)
var reBool = regexp.MustCompile(`(\w+)\s*=\s*(true|false)`)

func luaToJSON(content string) (map[string]any, error) {
	streams := map[string]any{}

	blocks := extractMakeStreamBlocks(content)
	for _, block := range blocks {
		s := parseLuaTable(block)
		id, _ := s["id"].(string)
		if id == "" {
			continue
		}
		streams[id] = s
	}

	return map[string]any{
		"streams":  streams,
		"settings": map[string]any{},
	}, nil
}

// extractMakeStreamBlocks finds all make_stream({...}) and make_channel({...}) bodies.
func extractMakeStreamBlocks(lua string) []string {
	var blocks []string
	for _, keyword := range []string{"make_stream", "make_channel"} {
		i := 0
		for i < len(lua) {
			idx := strings.Index(lua[i:], keyword)
			if idx < 0 {
				break
			}
			start := i + idx
			openBrace := strings.Index(lua[start:], "{")
			if openBrace < 0 {
				break
			}
			braceStart := start + openBrace
			depth, end := 0, -1
			for j := braceStart; j < len(lua); j++ {
				if lua[j] == '{' {
					depth++
				} else if lua[j] == '}' {
					depth--
					if depth == 0 {
						end = j
						break
					}
				}
			}
			if end < 0 {
				break
			}
			blocks = append(blocks, lua[braceStart+1:end])
			i = end + 1
		}
	}
	return blocks
}

var reNumber = regexp.MustCompile(`(\w+)\s*=\s*(-?\d+(?:\.\d+)?)[\s,;]`)

// parseLuaTable parses key=value pairs from a Lua table body.
// Handles semicolons as separators (make_channel style) in addition to commas.
func parseLuaTable(body string) map[string]any {
	result := map[string]any{}

	// arrays: key={"val1","val2"}
	reArray := regexp.MustCompile(`(\w+)\s*=\s*\{([^}]*)\}`)
	for _, m := range reArray.FindAllStringSubmatch(body, -1) {
		result[m[1]] = parseStringArray(m[2])
	}
	body = reArray.ReplaceAllString(body, "")

	// strings: key="value" or key='value'
	for _, m := range reString.FindAllStringSubmatch(body, -1) {
		result[m[1]] = m[2]
	}
	for _, m := range reStringSingle.FindAllStringSubmatch(body, -1) {
		result[m[1]] = m[2]
	}
	// booleans: key=true|false
	for _, m := range reBool.FindAllStringSubmatch(body, -1) {
		result[m[1]] = m[2] == "true"
	}
	// numbers: key=6 or key=11747
	for _, m := range reNumber.FindAllStringSubmatch(body+" ", -1) {
		if _, exists := result[m[1]]; !exists {
			result[m[1]] = m[2]
		}
	}
	return result
}

// parseStringArray splits a Lua array body into string slice.
func parseStringArray(body string) []string {
	var out []string
	// match "..." or '...' entries
	re := regexp.MustCompile(`["']([^"']*)["']`)
	for _, m := range re.FindAllStringSubmatch(body, -1) {
		out = append(out, m[1])
	}
	return out
}
